-- Create Tables matching the local Dexie.js database

CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" TEXT NOT NULL,
  type TEXT NOT NULL,
  items JSONB NOT NULL,
  "totalAmount" REAL NOT NULL,
  "paymentMethod" TEXT NOT NULL,
  "cashAmount" REAL DEFAULT 0,
  "bankAmount" REAL DEFAULT 0,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "isSynced" BOOLEAN DEFAULT TRUE,
  status TEXT,
  "branchId" TEXT,
  "customerName" TEXT,
  "tableNumber" TEXT
);

CREATE TABLE public.inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  unit TEXT NOT NULL,
  qty REAL NOT NULL,
  min REAL NOT NULL,
  "avgPrice" REAL NOT NULL,
  "isSynced" BOOLEAN DEFAULT TRUE,
  "branchQtys" JSONB
);

CREATE TABLE public."treasuryLogs" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  amount REAL NOT NULL,
  description TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "isSynced" BOOLEAN DEFAULT TRUE,
  "branchId" TEXT NOT NULL
);

CREATE TABLE public.invoices (
  id TEXT PRIMARY KEY,
  supplier TEXT NOT NULL,
  "itemId" BIGINT NOT NULL,
  qty REAL NOT NULL,
  "unitPrice" REAL NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL,
  "isSynced" BOOLEAN DEFAULT TRUE
);

CREATE TABLE public."branchRequests" (
  id TEXT PRIMARY KEY,
  branch TEXT NOT NULL,
  "itemId" BIGINT NOT NULL,
  "qtyRequested" REAL NOT NULL,
  status TEXT NOT NULL,
  "isSynced" BOOLEAN DEFAULT TRUE
);

CREATE TABLE public.employees (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  dob TEXT,
  branch TEXT,
  role TEXT,
  "accessLevel" TEXT,
  pin TEXT,
  "baseSalary" REAL,
  "deductHalfDay" REAL,
  "deductFullDay" REAL,
  "mealsEnabled" BOOLEAN,
  "mealsLimit" REAL,
  "cashWithdrawEnabled" BOOLEAN,
  "cashWithdrawLimit" REAL,
  "totalAdvance" REAL,
  "monthlyAdvanceCut" REAL,
  avatar TEXT,
  "documentId" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public."hrDeductions" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empName" TEXT NOT NULL,
  "empId" TEXT NOT NULL,
  amount REAL NOT NULL,
  reason TEXT NOT NULL,
  branch TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  status TEXT NOT NULL
);

CREATE TABLE public."tillTransfers" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fromTill" TEXT NOT NULL,
  "toTill" TEXT NOT NULL,
  "fromUser" TEXT NOT NULL,
  "toUser" TEXT NOT NULL,
  amount REAL NOT NULL,
  "branchId" TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public."shiftLogs" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cashierName" TEXT NOT NULL,
  "tillNo" TEXT NOT NULL,
  date TEXT NOT NULL,
  "openingBalance" REAL NOT NULL,
  "deliveredAmount" REAL NOT NULL,
  "expectedBalance" REAL NOT NULL,
  deficit REAL NOT NULL,
  surplus REAL NOT NULL,
  "branchId" TEXT NOT NULL
);

CREATE TABLE public."menuItems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price REAL NOT NULL,
  image TEXT,
  ingredients JSONB NOT NULL,
  cost REAL NOT NULL,
  "isAvailable" BOOLEAN DEFAULT TRUE
);

CREATE TABLE public."treasuryOutgoing" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  amount REAL NOT NULL,
  description TEXT,
  branch TEXT NOT NULL,
  "payeeName" TEXT,
  "referenceNo" TEXT,
  date TEXT NOT NULL,
  notes TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "isSynced" BOOLEAN DEFAULT TRUE
);

CREATE TABLE public."treasuryIncoming" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  amount REAL NOT NULL,
  description TEXT,
  branch TEXT NOT NULL,
  date TEXT NOT NULL,
  notes TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "isSynced" BOOLEAN DEFAULT TRUE
);

CREATE TABLE public.suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  address TEXT,
  category TEXT,
  notes TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public."purchaseRequests" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "requestNumber" TEXT NOT NULL,
  "supplierId" BIGINT,
  "supplierName" TEXT NOT NULL,
  "itemId" BIGINT,
  "itemName" TEXT NOT NULL,
  qty REAL NOT NULL,
  unit TEXT NOT NULL,
  "unitPrice" REAL NOT NULL,
  "totalAmount" REAL NOT NULL,
  branch TEXT NOT NULL,
  notes TEXT,
  status TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "approvedAt" TEXT,
  "approvedBy" TEXT,
  "paymentOrderId" BIGINT
);

CREATE TABLE public."paymentOrders" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "voucherNumber" TEXT NOT NULL,
  "purchaseRequestId" BIGINT NOT NULL,
  "requestNumber" TEXT NOT NULL,
  "supplierName" TEXT NOT NULL,
  "itemName" TEXT NOT NULL,
  qty REAL NOT NULL,
  unit TEXT NOT NULL,
  "unitPrice" REAL NOT NULL,
  "totalAmount" REAL NOT NULL,
  branch TEXT NOT NULL,
  status TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "paidAt" TEXT,
  "paidBy" TEXT,
  notes TEXT
);

CREATE TABLE public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  address TEXT,
  "preferredBranch" TEXT,
  notes TEXT,
  "totalOrders" BIGINT DEFAULT 0,
  "lastOrderAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public."callCenterOrders" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" TEXT NOT NULL,
  "customerName" TEXT NOT NULL,
  "customerPhone" TEXT NOT NULL,
  "targetBranch" TEXT NOT NULL,
  "orderType" TEXT NOT NULL,
  address TEXT,
  items JSONB NOT NULL,
  "totalAmount" REAL NOT NULL,
  notes TEXT,
  status TEXT NOT NULL,
  "agentName" TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "approvedAt" TEXT,
  "approvedBy" TEXT
);

CREATE TABLE public.settings (
  id TEXT PRIMARY KEY,
  "deliveryFee" REAL,
  "taxRate" REAL,
  "hospitalityLimit" REAL,
  "branchesControl" JSONB
);

-- Turn off Row Level Security (RLS) to allow the app to function properly during setup phase
-- Or you can keep it off since the app might not use Supabase Auth yet.
-- Warning: Unsafe for production unless you handle authentication
